// Generated by CoffeeScript 1.8.0
(function() {
  document.write("<script type=\"text/javascript\" src=\"../expand.js\"></script>");

  $('.switch').click(function() {
    return $.getScript('../expand.js', function() {
      return console.log('load expand.js');
    });
  });

}).call(this);

//# sourceMappingURL=load.js.map
